version: '3.4'

services:
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/ApiGateway/Dockerfile

  identity:
    image: ${DOCKER_REGISTRY-}identity
    build:
      context: .
      dockerfile: Identity/Identity.Api/Dockerfile

  consumer:
    image: ${DOCKER_REGISTRY-}consumer
    build:
      context: .
      dockerfile: Consumer/Consumer.Api/Dockerfile

  admin:
    image: ${DOCKER_REGISTRY-}admin
    build:
      context: .
      dockerfile: Admin/Admin.Api/Dockerfile

  provider:
    image: ${DOCKER_REGISTRY-}provider
    build:
      context: .
      dockerfile: Provider/Provider.Api/Dockerfile

  services:
    image: ${DOCKER_REGISTRY-}services
    build:
      context: .
      dockerfile: Services/Services.Api/Dockerfile